<%@ Page 
  Language="C#" 
  AutoEventWireup="true" 
  CodeBehind="WebForm1.aspx.cs" 
  UnobtrusiveValidationMode="None"
  Inherits="WebApp_Unit_6.WebForm1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Unidad 6</title>
    <%--<link rel="stylesheet" type="text/css" href="WebApp-1.css"/>--%>
</head>
<body>
  <h1>Grid View</h1>

  <form id="form1" runat="server">
      <div>
        <asp:GridView ID="gridLibros" runat="server" 
          AutoGenerateColumns="False"
          AutoGenerateSelectButton="True" 
          OnSelectedIndexChanging="gridLibros_SelectedIndexChanging" 
          AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
          OnRowDeleting="gridLibros_RowDeleting" 
          OnRowEditing="gridLibros_RowEditing" OnRowCancelingEdit="gridLibros_RowCancelingEdit" OnRowUpdating="gridLibros_RowUpdating" AllowPaging="True" CellPadding="4" ForeColor="#333333" GridLines="None" OnPageIndexChanging="gridLibros_PageIndexChanging" OnRowCommand="gridLibros_RowCommand" PageSize="2" >
          <%-- Columnas --%>
          <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
          <Columns>
            <%-- Columna: LIBRO ID --%>
            <asp:TemplateField HeaderText="Libro (ID)">
              <%-- EDIT --%>
              <EditItemTemplate>
                <asp:Label ID="edit_itemTemp_idLibro" runat="server" Text='<%# Bind("IdLibro") %>'></asp:Label>
              </EditItemTemplate>
              <%-- ADD --%>
              <ItemTemplate>
                <asp:Label ID="itemTemplate_IDLibro" runat="server" Text='<%# Bind("IdLibro") %>'></asp:Label>
              </ItemTemplate>
            </asp:TemplateField>

            <%-- Columna: TEMA ID --%>
            <asp:TemplateField HeaderText="Tema (ID)">
              <%-- EDIT --%>
              <EditItemTemplate>
                <asp:Label ID="edit_itemTemp_IDTema" runat="server" Text='<%# Bind("IdTema") %>'></asp:Label>
              </EditItemTemplate>
              <%-- ADD --%>
              <ItemTemplate>
                <asp:Label ID="itemTemplate_IDTema" runat="server" Text='<%# Bind("IdTema") %>'></asp:Label>
              </ItemTemplate>
            </asp:TemplateField>

            <%-- Columna: TITULO--%>
            <asp:TemplateField HeaderText="Titulo">
              <%-- EDIT --%>
              <EditItemTemplate>
                <asp:TextBox ID="edit_txtBox_Titulo" runat="server" Text='<%# Bind("Titulo") %>'></asp:TextBox>
              </EditItemTemplate>
              <%-- ADD --%>
              <ItemTemplate>
                <asp:Label ID="itemTemplate_Titulo" runat="server" Text='<%# Bind("Titulo") %>'></asp:Label>
              </ItemTemplate>
            </asp:TemplateField>

            <%-- Columna: PRECIO--%>
            <asp:TemplateField HeaderText="Precio">
              <%-- EDIT --%>
              <EditItemTemplate>
                <asp:TextBox ID="edit_txtBox_Precio" runat="server" Text='<%# Bind("Precio") %>'></asp:TextBox>
              </EditItemTemplate>
              <%-- ADD --%>
              <ItemTemplate>
                <asp:Label ID="itemTemplate_Precio" runat="server" Text='<%# Bind("Precio") %>'></asp:Label>
              </ItemTemplate>
            </asp:TemplateField>

            <%-- Columna: AUTOR--%>
            <asp:TemplateField HeaderText="Autor">
              <%-- EDIT --%>
              <EditItemTemplate>
                <asp:TextBox ID="edit_txtBox_Autor" runat="server" Text='<%# Bind("Autor") %>'></asp:TextBox>
              </EditItemTemplate>
              <%-- ADD --%>
              <ItemTemplate>
                <asp:Label ID="itemTemplate_Autor" runat="server" Text='<%# Bind("Autor") %>'></asp:Label>
              </ItemTemplate>
            </asp:TemplateField>

            <asp:ButtonField ButtonType="Button" CommandName="buyEnvent" Text="Comprar" />

          </Columns>
          <EditRowStyle BackColor="#999999" />
          <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
          <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
          <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
          <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
          <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
          <SortedAscendingCellStyle BackColor="#E9E7E2" />
          <SortedAscendingHeaderStyle BackColor="#506C8C" />
          <SortedDescendingCellStyle BackColor="#FFFDF8" />
          <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
        </asp:GridView>

        <hr />
        <asp:Label ID="lblRowSelected" runat="server" Text=""></asp:Label>
        <hr />

        <%-- VARIABLE SESION --%>
        <h3>Variable Sesion</h3>
        <div class="contenedor_variableSesion">
          <span>Ingrese sus nonbre: </span>
           <asp:TextBox runat="server" ID="txtBoxNameUser"></asp:TextBox>
           <asp:Button runat="server" ID="btnSend" Text="Enviar" OnClick="btnSend_Click"/> 
        </div>

        <hr />
        <asp:HyperLink ID="linkCountClick" runat="server" NavigateUrl="~/WebApp-2.aspx">WEB APP - 2</asp:HyperLink>
         <%-- VARIBLE APLICACION --%>
        <h3>Variable Aplicacion</h3>
        <div class="contenedor_variableApp">
          <span>Contador click
           <asp:Button runat="server" ID="btnCountClick" Text="Contar" OnClick="btnCountClick_Click"/> 
          </span>
          <br />
        </div>
        <hr />
        <asp:HyperLink ID="linkAddData" runat="server" NavigateUrl="~/WebApp-3.aspx">WEB APP - 3</asp:HyperLink>
      <%-- VARIABLE DATA --%>
        <h3>Variable Data</h3>
        <div class="contenedor_varaibleDarta">
          <span>Ingrese su Pais: 
            <asp:TextBox runat="server" ID="txtBoxCountry"></asp:TextBox>
          </span>
          <br />
          <span>Ingrese su Ciudad
            <asp:TextBox runat="server" ID="txtBoxCity"></asp:TextBox>
          </span>
          <br />
         <asp:Button runat="server" ID="btnAddData" text="Agregar" OnClick="btnAddData_Click"/>
        </div>
      </div>
  </form>
</body>
</html>
