<%@ Page 
  Language="C#" 
  AutoEventWireup="true" 
  CodeBehind="WebForm1.aspx.cs" 
  UnobtrusiveValidationMode="None"
  Inherits="WebApp_Unit_6.WebForm1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Unidad 6</title>
    <%--<link rel="stylesheet" type="text/css" href="WebApp-1.css"/>--%>
</head>
<body>
  <h1>Grid View</h1>

  <form id="form1" runat="server">
      <div>
        <asp:GridView ID="gridLibros" runat="server" 
          AutoGenerateColumns="False"
          AutoGenerateSelectButton="True" 
          OnSelectedIndexChanging="gridLibros_SelectedIndexChanging" 
          AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
          OnRowDeleting="gridLibros_RowDeleting" 
          OnRowEditing="gridLibros_RowEditing" >
          <%-- Columnas --%>
          <Columns>
            <%-- Columna: LIBRO ID --%>
            <asp:TemplateField HeaderText="Libro (ID)">
              <%-- EDIT --%>
              <EditItemTemplate>
                <asp:Label ID="edit_itemTemp_idLibro" runat="server" Text='<%# Bind("IdLibro") %>'></asp:Label>
              </EditItemTemplate>
              <%-- ADD --%>
              <ItemTemplate>
                <asp:Label ID="itemTemplate_IDLibro" runat="server" Text='<%# Bind("IdLibro") %>'></asp:Label>
              </ItemTemplate>
            </asp:TemplateField>
            <%-- Columna: TEMA ID --%>
            <asp:TemplateField HeaderText="Tema (ID)">
              <%-- EDIT --%>
              <EditItemTemplate>
                <asp:Label ID="edit_itemTemp_IDTema" runat="server" Text='<%# Bind("IdTema") %>'></asp:Label>
              </EditItemTemplate>
              <%-- ADD --%>
              <ItemTemplate>
                <asp:Label ID="itemTemplate_IDTema" runat="server" Text='<%# Bind("IdTema") %>'></asp:Label>
              </ItemTemplate>
            </asp:TemplateField>
            <%-- Columna: TITULO--%>
            <asp:TemplateField HeaderText="Titulo">
              <%-- EDIT --%>
              <EditItemTemplate>
                <asp:TextBox ID="edit_txtBox_Titulo" runat="server" Text='<%# Bind("Titulo") %>'></asp:TextBox>
              </EditItemTemplate>
              <%-- ADD --%>
              <ItemTemplate>
                <asp:Label ID="itemTemplate_Titulo" runat="server" Text='<%# Bind("Titulo") %>'></asp:Label>
              </ItemTemplate>
            </asp:TemplateField>
            <%-- Columna: PRECIO--%>
            <asp:TemplateField HeaderText="Precio">
              <%-- EDIT --%>
              <EditItemTemplate>
                <asp:TextBox ID="edit_txtBox_Precio" runat="server" Text='<%# Bind("Precio") %>'></asp:TextBox>
              </EditItemTemplate>
              <%-- ADD --%>
              <ItemTemplate>
                <asp:Label ID="itemTemplate_Precio" runat="server" Text='<%# Bind("Precio") %>'></asp:Label>
              </ItemTemplate>
            </asp:TemplateField>
            <%-- Columna: AUTOR--%>
            <asp:TemplateField HeaderText="Autor">
              <%-- EDIT --%>
              <EditItemTemplate>
                <asp:TextBox ID="edit_txtBox_Autor" runat="server" Text='<%# Bind("Autor") %>'></asp:TextBox>
              </EditItemTemplate>
              <%-- ADD --%>
              <ItemTemplate>
                <asp:Label ID="itemTemplate_Autor" runat="server" Text='<%# Bind("Autor") %>'></asp:Label>
              </ItemTemplate>
            </asp:TemplateField>
          </Columns>
        </asp:GridView>
        <hr />
        <asp:Label ID="lblRowSelected" runat="server" Text=""></asp:Label>
      </div>
  </form>
</body>
</html>
